// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookmarkFormController from "./bookmark_form_controller"
application.register("bookmark-form", BookmarkFormController)

import ListFormController from "./list_form_controller"
application.register("list-form", ListFormController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

require("./aos_controller")
