// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AosController from "./aos_controller"
application.register("aos", AosController)

import BookmarkFormController from "./bookmark_form_controller"
application.register("bookmark-form", BookmarkFormController)

import ListFormController from "./list_form_controller"
application.register("list-form", ListFormController)

import SlimController from "./slim_controller"
application.register("slim", SlimController)
